### ISSUE TITLE
Ghost damage

### ISSUE THREAD

**Issue by TommySoucy** [TommySoucy/H3MP#126]
A player fires
Sends fire action to other players
Other players fire
Since waiting for the fire, other players received updates for the firing player's position, possibly putting their bodies in front of the remote shot, causing themselves damage?

**Comment by TommySoucy** [comment]
```
[Info   :      H3MP]    Not controller
[Info   :      H3MP]            Set in objects array, didnt have data yet
[Info   :      H3MP] Client adding new tracked object with waiting local index: 4294967295, tracked ID: 86, and type ID: TrackedItemData
[Info   :      H3MP]    Not controller
[Info   :      H3MP]            Set in objects array, didnt have data yet
[Info   :      H3MP] Client adding new tracked object with waiting local index: 4294967295, tracked ID: 88, and type ID: TrackedItemData
[Info   :      H3MP]    Not controller
[Info   :      H3MP]            Set in objects array, didnt have data yet
[Info   :      H3MP] Sending player damage to 0
   at System.Environment.get_StackTrace()
   at H3MP.Networking.ClientSend.PlayerDamage(Int32 clientID, Byte part, FistVR.Damage damage)
   at H3MP.PlayerManager.Damage(Part part, FistVR.Damage damage)
   at H3MP.PlayerHitbox.Damage(FistVR.Damage dam)
   at FistVR.BallisticProjectile.DMD<FistVR.BallisticProjectile::MoveBullet>(FistVR.BallisticProjectile , Single )
   at FistVR.BallisticProjectile.UpdateBulletPath()
   at FistVR.BallisticProjectile.DMD<FistVR.BallisticProjectile::Fire>(FistVR.BallisticProjectile , Single , Vector3 , FistVR.FVRFireArm , Boolean )
   at FistVR.FVRFireArm.DMD<FistVR.FVRFireArm::Fire>(FistVR.FVRFireArm , FistVR.FVRFireArmChamber , UnityEngine.Transform , Boolean , Single , Single )
   at FistVR.Handgun.Fire()
   at H3MP.Tracking.TrackedItem.FireHandgun(Int32 chamberIndex)
   at H3MP.Networking.ClientHandle.WeaponFire(H3MP.Networking.Packet packet)
   at H3MP.Networking.Client+TCP+<>c__DisplayClass8_0.<HandleData>b__0()
   at H3MP.Networking.ThreadManager.UpdateMain()
   at H3MP.Networking.ThreadManager.Update()
[Info   :      H3MP] Sosig 96 dropped item in hand: 0
[Info   :      H3MP] Sending player damage to 0
   at System.Environment.get_StackTrace()
   at H3MP.Networking.ClientSend.PlayerDamage(Int32 clientID, Byte part, FistVR.Damage damage)
   at H3MP.PlayerManager.Damage(Part part, FistVR.Damage damage)
   at H3MP.PlayerHitbox.Damage(FistVR.Damage dam)
   at FistVR.BallisticProjectile.DMD<FistVR.BallisticProjectile::MoveBullet>(FistVR.BallisticProjectile , Single )
   at FistVR.BallisticProjectile.UpdateBulletPath()
   at FistVR.BallisticProjectile.DMD<FistVR.BallisticProjectile::Fire>(FistVR.BallisticProjectile , Single , Vector3 , FistVR.FVRFireArm , Boolean )
   at FistVR.FVRFireArm.DMD<FistVR.FVRFireArm::Fire>(FistVR.FVRFireArm , FistVR.FVRFireArmChamber , UnityEngine.Transform , Boolean , Single , Single )
   at FistVR.Handgun.Fire()
   at H3MP.Tracking.TrackedItem.FireHandgun(Int32 chamberIndex)
   at H3MP.Networking.ClientHandle.WeaponFire(H3MP.Networking.Packet packet)
   at H3MP.Networking.Client+TCP+<>c__DisplayClass8_0.<HandleData>b__0()
   at H3MP.Networking.ThreadManager.UpdateMain()
   at H3MP.Networking.ThreadManager.Update()
[Info   :      H3MP] Sosig 96 drop item in slot: 0
[Info   :      H3MP] Sosig 95 dropped item in hand: 0
[Info   :      H3MP] Sosig 96 dropped item in hand: 1
[Info   :      H3MP] Sosig 96 dropped item in hand: 0
[Info   :      H3MP] Sending player damage to 0
   at System.Environment.get_StackTrace()
   at H3MP.Networking.ClientSend.PlayerDamage(Int32 clientID, Byte part, FistVR.Damage damage)
   at H3MP.PlayerManager.Damage(Part part, FistVR.Damage damage)
   at H3MP.PlayerHitbox.Damage(FistVR.Damage dam)
   at FistVR.BallisticProjectile.DMD<FistVR.BallisticProjectile::MoveBullet>(FistVR.BallisticProjectile , Single )
   at FistVR.BallisticProjectile.UpdateBulletPath()
   at FistVR.BallisticProjectile.DMD<FistVR.BallisticProjectile::Fire>(FistVR.BallisticProjectile , Single , Vector3 , FistVR.FVRFireArm , Boolean )
   at FistVR.FVRFireArm.DMD<FistVR.FVRFireArm::Fire>(FistVR.FVRFireArm , FistVR.FVRFireArmChamber , UnityEngine.Transform , Boolean , Single , Single )
   at FistVR.Handgun.Fire()
   at H3MP.Tracking.TrackedItem.FireHandgun(Int32 chamberIndex)
   at H3MP.Networking.ClientHandle.WeaponFire(H3MP.Networking.Packet packet)
   at H3MP.Networking.Client+TCP+<>c__DisplayClass8_0.<HandleData>b__0()
   at H3MP.Networking.ThreadManager.UpdateMain()
   at H3MP.Networking.ThreadManager.Update()
```

**Comment by TommySoucy** [comment]
reason why this ghost damage is usually very little, it because it hits the hands, which has a multiplier for it to make less damage than body shots for example. 

Will need to review the damage process again. This was probably caused by the changes we made so that other players could get damage effects when shooting at remotely controlled steel targets.

**Comment by TommySoucy** [comment]
This is caused because we assume damage should be handled client side because the damageable cannot be found in trackedObjectByDamageable. 

Player hitboxes never get added to this dict because they are not tracked objects.

We can fix this by either

- Making the players just another type of tracked object, which would work pretty well but require a bit of restructuring
- When we decide whether to process damage or not, we should also manually check if damageable isn't a player hitbox
